/// Flutter icons MarkerIconFirst
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MarkerIconFirst
///      fonts:
///       - asset: fonts/MarkerIconFirst.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MarkerIconFirst {
  MarkerIconFirst._();

  static const _kFontFam = 'MarkerIconFirst';
  static const String? _kFontPkg = null;

  static const IconData outline = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filled = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
